// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kllrmcmgnznoxnpvwbzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtsbHJtY21nbnpub3hucHZ3YnprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5MTc1NzAsImV4cCI6MjA3MTQ5MzU3MH0.l0h4CDrcwVbxfdMfqQfjDdQBzfRdCcJlx8gOsNMXVKo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});